name: Update Latest Follower

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

# TIGA BARIS INI PENTING: Memberikan izin bot untuk menyimpan perubahan
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Diupdate ke v4 agar warning Node.js hilang
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Diupdate ke v5 agar warning Node.js hilang
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Update Script
        run: python update_follower.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update latest follower"
          git push
